In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

Read Data From CSV

In [2]:
df = pd.read_pickle('all_data.pkl')
print(df)

         srch_id            date_time  site_id  visitor_location_country_id  \
0              1  2013-04-04 08:32:15       12                          187
1              1  2013-04-04 08:32:15       12                          187
2              1  2013-04-04 08:32:15       12                          187
3              1  2013-04-04 08:32:15       12                          187
4              1  2013-04-04 08:32:15       12                          187
5              1  2013-04-04 08:32:15       12                          187
6              1  2013-04-04 08:32:15       12                          187
7              1  2013-04-04 08:32:15       12                          187
8              1  2013-04-04 08:32:15       12                          187
9              1  2013-04-04 08:32:15       12                          187
10             1  2013-04-04 08:32:15       12                          187
11             1  2013-04-04 08:32:15       12                          187
12             1  2013-04-04 08:32:15       12                          187
13             1  2013-04-04 08:32:15       12                          187
14             1  2013-04-04 08:32:15       12                          187
15             1  2013-04-04 08:32:15       12                          187
16             1  2013-04-04 08:32:15       12                          187
17             1  2013-04-04 08:32:15       12                          187
18             1  2013-04-04 08:32:15       12                          187
19             1  2013-04-04 08:32:15       12                          187
20             1  2013-04-04 08:32:15       12                          187
21             1  2013-04-04 08:32:15       12                          187
22             1  2013-04-04 08:32:15       12                          187
23             1  2013-04-04 08:32:15       12                          187
24             1  2013-04-04 08:32:15       12                          187
25             1  2013-04-04 08:32:15       12                          187
26             1  2013-04-04 08:32:15       12                          187
27             1  2013-04-04 08:32:15       12                          187
28             4  2012-12-31 08:59:22        5                          219
29             4  2012-12-31 08:59:22        5                          219
...          ...                  ...      ...                          ...
4958317   332784  2013-06-18 14:35:24       24                          219
4958318   332784  2013-06-18 14:35:24       24                          219
4958319   332784  2013-06-18 14:35:24       24                          219
4958320   332784  2013-06-18 14:35:24       24                          219
4958321   332784  2013-06-18 14:35:24       24                          219
4958322   332784  2013-06-18 14:35:24       24                          219
4958323   332784  2013-06-18 14:35:24       24                          219
4958324   332784  2013-06-18 14:35:24       24                          219
4958325   332784  2013-06-18 14:35:24       24                          219
4958326   332784  2013-06-18 14:35:24       24                          219
4958327   332784  2013-06-18 14:35:24       24                          219
4958328   332784  2013-06-18 14:35:24       24                          219
4958329   332784  2013-06-18 14:35:24       24                          219
4958330   332784  2013-06-18 14:35:24       24                          219
4958331   332784  2013-06-18 14:35:24       24                          219
4958332   332784  2013-06-18 14:35:24       24                          219
4958333   332784  2013-06-18 14:35:24       24                          219
4958334   332784  2013-06-18 14:35:24       24                          219
4958335   332784  2013-06-18 14:35:24       24                          219
4958336   332784  2013-06-18 14:35:24       24                          219
4958337   332784  2013-06-18 14:35:24       24                          219
4958338   332784  2013-06-18 14:35:24       24                          219
4958339   332784  2013-06-18 14:35:24       24                          219
4958340   332784  2013-06-18 14:35:24       24                          219
4958341   332785  2013-06-30 19:55:18        5                          219
4958342   332785  2013-06-30 19:55:18        5                          219
4958343   332785  2013-06-30 19:55:18        5                          219
4958344   332785  2013-06-30 19:55:18        5                          219
4958345   332785  2013-06-30 19:55:18        5                          219
4958346   332785  2013-06-30 19:55:18        5                          219

         visitor_hist_starrating  visitor_hist_adr_usd  prop_country_id  \
0                            NaN                   NaN              219
1                            NaN                   NaN              219
2                            NaN                   NaN              219
3                            NaN                   NaN              219
4                            NaN                   NaN              219
5                            NaN                   NaN              219
6                            NaN                   NaN              219
7                            NaN                   NaN              219
8                            NaN                   NaN              219
9                            NaN                   NaN              219
10                           NaN                   NaN              219
11                           NaN                   NaN              219
12                           NaN                   NaN              219
13                           NaN                   NaN              219
14                           NaN                   NaN              219
15                           NaN                   NaN              219
16                           NaN                   NaN              219
17                           NaN                   NaN              219
18                           NaN                   NaN              219
19                           NaN                   NaN              219
20                           NaN                   NaN              219
21                           NaN                   NaN              219
22                           NaN                   NaN              219
23                           NaN                   NaN              219
24                           NaN                   NaN              219
25                           NaN                   NaN              219
26                           NaN                   NaN              219
27                           NaN                   NaN              219
28                           NaN                   NaN              219
29                           NaN                   NaN              219
...                          ...                   ...              ...
4958317                      NaN                   NaN              100
4958318                      NaN                   NaN              100
4958319                      NaN                   NaN              100
4958320                      NaN                   NaN              100
4958321                      NaN                   NaN              100
4958322                      NaN                   NaN              100
4958323                      NaN                   NaN              100
4958324                      NaN                   NaN              100
4958325                      NaN                   NaN              100
4958326                      NaN                   NaN              100
4958327                      NaN                   NaN              100
4958328                      NaN                   NaN              100
4958329                      NaN                   NaN              100
4958330                      NaN                   NaN              100
4958331                      NaN                   NaN              100
4958332                      NaN                   NaN              100
4958333                      NaN                   NaN              100
4958334                      NaN                   NaN              100
4958335                      NaN                   NaN              100
4958336                      NaN                   NaN              100
4958337                      NaN                   NaN              100
4958338                      NaN                   NaN              100
4958339                      NaN                   NaN              100
4958340                      NaN                   NaN              100
4958341                      NaN                   NaN              219
4958342                      NaN                   NaN              219
4958343                      NaN                   NaN              219
4958344                      NaN                   NaN              219
4958345                      NaN                   NaN              219
4958346                      NaN                   NaN              219

         prop_id  prop_starrating  prop_review_score      ...       \
0            893                3                3.5      ...
1          10404                4                4.0      ...
2          21315                3                4.5      ...
3          27348                2                4.0      ...
4          29604                4                3.5      ...
5          30184                4                4.5      ...
6          44147                3                3.5      ...
7          50984                2                0.0      ...
8          53341                4                4.0      ...
9          56880                4                4.0      ...
10         59267                3                0.0      ...
11         59526                3                3.5      ...
12         68914                2                3.0      ...
13         74474                3                4.5      ...
14         81437                3                4.0      ...
15         85728                2                3.0      ...
16         88096                4                4.0      ...
17         88127                3                3.0      ...
18         88218                4                3.5      ...
19         89073                4                4.0      ...
20         95166                3                4.0      ...
21         95307                4                3.5      ...
22         97247                2                3.5      ...
23        107872                2                3.5      ...
24        111000                3                4.5      ...
25        111106                3                2.5      ...
26        114766                2                3.5      ...
27        122844                3                4.5      ...
28          3625                4                4.0      ...
29         11622                4                4.0      ...
...          ...              ...                ...      ...
4958317    21150                3                4.0      ...
4958318    25223                4                4.0      ...
4958319    28943                4                3.5      ...
4958320    31381                4                4.5      ...
4958321    34966                3                4.5      ...
4958322    48216                4                5.0      ...
4958323    48512                4                4.5      ...
4958324    50151                5                4.5      ...
4958325    51555                4                4.5      ...
4958326    51585                4                4.5      ...
4958327    51653                4                4.5      ...
4958328    52463                4                4.5      ...
4958329    55158                5                4.5      ...
4958330    58015                4                4.5      ...
4958331    78171                2                0.0      ...
4958332    82051                3                3.5      ...
4958333    88307                2                3.0      ...
4958334    89802                2                4.0      ...
4958335    90665                4                4.5      ...
4958336   114177                4                4.5      ...
4958337   115562                4                4.0      ...
4958338   121275                4                4.0      ...
4958339   128677                3                3.5      ...
4958340   140304                3                4.0      ...
4958341    55110                3                1.0      ...
4958342    77700                3                4.0      ...
4958343    88083                3                4.0      ...
4958344    94508                3                3.5      ...
4958345   128360                3                5.0      ...
4958346   134949                3                2.5      ...

         comp6_rate_percent_diff  comp7_rate  comp7_inv  \
0                            NaN         NaN        NaN
1                            NaN         NaN        NaN
2                            NaN         NaN        NaN
3                            NaN         NaN        NaN
4                            NaN         NaN        NaN
5                            NaN         NaN        NaN
6                            NaN         NaN        NaN
7                            NaN         NaN        NaN
8                            NaN         NaN        NaN
9                            NaN         NaN        NaN
10                           NaN         NaN        NaN
11                           NaN         NaN        NaN
12                           NaN         NaN        NaN
13                           NaN         NaN        NaN
14                           NaN         NaN        NaN
15                           NaN         NaN        NaN
16                           NaN         NaN        NaN
17                           NaN         NaN        NaN
18                           NaN         NaN        NaN
19                           NaN         NaN        NaN
20                           NaN         NaN        NaN
21                           NaN         NaN        NaN
22                           NaN         NaN        NaN
23                           NaN         NaN        NaN
24                           NaN         NaN        NaN
25                           NaN         NaN        NaN
26                           NaN         NaN        NaN
27                           NaN         NaN        NaN
28                           NaN         NaN        NaN
29                           NaN         NaN        NaN
...                          ...         ...        ...
4958317                      NaN         NaN        NaN
4958318                      NaN         NaN        NaN
4958319                      NaN         NaN        NaN
4958320                      NaN         NaN        NaN
4958321                      NaN         NaN        NaN
4958322                      NaN         NaN        NaN
4958323                      NaN         NaN        NaN
4958324                      NaN         NaN        NaN
4958325                      NaN         NaN        NaN
4958326                      NaN         NaN        NaN
4958327                      NaN         NaN        NaN
4958328                      NaN         NaN        NaN
4958329                      NaN         NaN        NaN
4958330                      NaN         NaN        NaN
4958331                      NaN         NaN        NaN
4958332                      NaN         NaN        NaN
4958333                      NaN         NaN        NaN
4958334                      NaN         NaN        NaN
4958335                      NaN         NaN        NaN
4958336                      NaN         NaN        NaN
4958337                      NaN         NaN        NaN
4958338                      NaN         NaN        NaN
4958339                      NaN         NaN        NaN
4958340                      NaN         NaN        NaN
4958341                      NaN         NaN        NaN
4958342                      NaN         NaN        NaN
4958343                      NaN         NaN        NaN
4958344                      NaN         NaN        NaN
4958345                      NaN         NaN        NaN
4958346                      NaN         NaN        NaN

         comp7_rate_percent_diff  comp8_rate  comp8_inv  \
0                            NaN         0.0        0.0
1                            NaN         0.0        0.0
2                            NaN         0.0        0.0
3                            NaN        -1.0        0.0
4                            NaN         0.0        0.0
5                            NaN         0.0        0.0
6                            NaN         0.0        0.0
7                            NaN         NaN        NaN
8                            NaN         0.0        0.0
9                            NaN         0.0        0.0
10                           NaN         0.0        0.0
11                           NaN         1.0        0.0
12                           NaN         0.0        0.0
13                           NaN         0.0        0.0
14                           NaN         0.0        0.0
15                           NaN         0.0        0.0
16                           NaN         0.0        0.0
17                           NaN         0.0        0.0
18                           NaN         0.0        0.0
19                           NaN         0.0        0.0
20                           NaN         0.0        0.0
21                           NaN        -1.0        0.0
22                           NaN        -1.0        0.0
23                           NaN         0.0        0.0
24                           NaN         0.0        0.0
25                           NaN         0.0        0.0
26                           NaN         NaN        NaN
27                           NaN         0.0        0.0
28                           NaN         NaN        NaN
29                           NaN         NaN        NaN
...                          ...         ...        ...
4958317                      NaN         0.0        0.0
4958318                      NaN         NaN        NaN
4958319                      NaN         0.0        0.0
4958320                      NaN         NaN        NaN
4958321                      NaN         NaN        NaN
4958322                      NaN         NaN        NaN
4958323                      NaN         NaN        NaN
4958324                      NaN         NaN        NaN
4958325                      NaN         NaN        NaN
4958326                      NaN         NaN        NaN
4958327                      NaN         NaN        NaN
4958328                      NaN         NaN        NaN
4958329                      NaN         NaN        NaN
4958330                      NaN         NaN        NaN
4958331                      NaN         NaN        NaN
4958332                      NaN         1.0        0.0
4958333                      NaN         NaN        NaN
4958334                      NaN         0.0        0.0
4958335                      NaN         NaN        NaN
4958336                      NaN        -1.0        0.0
4958337                      NaN         NaN        NaN
4958338                      NaN         0.0        0.0
4958339                      NaN         0.0        0.0
4958340                      NaN         NaN        NaN
4958341                      NaN         NaN        NaN
4958342                      NaN         NaN        NaN
4958343                      NaN         NaN        NaN
4958344                      NaN         NaN        NaN
4958345                      NaN         NaN        NaN
4958346                      NaN         NaN        NaN


Correlation Matrix of Raw Data:

In [3]:
# df.dropna(inplace=True,axis='columns')
property_attributes = ['prop_country_id', 'prop_starrating', 'prop_review_score', 'prop_brand_bool',
                           'prop_location_score1', 'prop_location_score2', 'prop_log_historical_price',
                           'promotion_flag', 'srch_query_affinity_score',]

# df.columns
# df2 = df[property_attributes].dropna()
# print(df[df['prop_starrating'] == 0].sum())
print(df.isna().sum())
# corrMatrix = df2.corr()
# sns.heatmap(corrMatrix, annot=True)
# fig = plt.gcf()
# fig.set_size_inches(60, 60)
# plt.show()

srch_id                              0
date_time                            0
site_id                              0
visitor_location_country_id          0
visitor_hist_starrating        4706481
visitor_hist_adr_usd           4705359
prop_country_id                      0
prop_id                              0
prop_starrating                      0
prop_review_score                 7364
prop_brand_bool                      0
prop_location_score1                 0
prop_location_score2           1090348
prop_log_historical_price            0
position                             0
price_usd                            0
promotion_flag                       0
srch_destination_id                  0
srch_length_of_stay                  0
srch_booking_window                  0
srch_adults_count                    0
srch_children_count                  0
srch_room_count                      0
srch_saturday_night_bool             0
srch_query_affinity_score      4640941
orig_destination_distance      1607782
random_bool                          0
comp1_rate                     4838417
comp1_inv                      4828788
comp1_rate_percent_diff        4863908
comp2_rate                     2933675
comp2_inv                      2828078
comp2_rate_percent_diff        4402109
comp3_rate                     3424059
comp3_inv                      3307357
comp3_rate_percent_diff        4485550
comp4_rate                     4650969
comp4_inv                      4614684
comp4_rate_percent_diff        4827261
comp5_rate                     2735974
comp5_inv                      2598327
comp5_rate_percent_diff        4117248
comp6_rate                     4718190
comp6_inv                      4697371
comp6_rate_percent_diff        4862173
comp7_rate                     4642999
comp7_inv                      4601925
comp7_rate_percent_diff        4819832
comp8_rate                     3041693
comp8_inv                      2970844
comp8_rate_percent_diff        4343617
click_bool                           0
gross_bookings_usd             4819957
booking_bool                         0
dtype: int64

In [46]:

corrMatrix

,prop_country_id,prop_starrating,prop_review_score,prop_brand_bool,prop_location_score1,prop_location_score2,prop_log_historical_price,promotion_flag,srch_query_affinity_score
prop_country_id,1.000000,-0.203206,-0.008223,0.249564,-0.185704,-0.024934,-0.018883,-0.100476,0.014776
prop_starrating,-0.203206,1.000000,0.393581,-0.002776,0.319010,0.095411,0.172054,0.160198,0.028126
prop_review_score,-0.008223,0.393581,1.000000,0.134474,0.120747,0.058638,0.105421,0.012447,0.011806
prop_brand_bool,0.249564,-0.002776,0.134474,1.000000,-0.197557,-0.106140,-0.025363,-0.178336,-0.029269
prop_location_score1,-0.185704,0.319010,0.120747,-0.197557,1.000000,0.389582,0.133787,0.185421,0.034492
prop_location_score2,-0.024934,0.095411,0.058638,-0.106140,0.389582,1.000000,0.054840,0.051506,0.075046
prop_log_historical_price,-0.018883,0.172054,0.105421,-0.025363,0.133787,0.054840,1.000000,0.031190,0.021229
promotion_flag,-0.100476,0.160198,0.012447,-0.178336,0.185421,0.051506,0.031190,1.000000,0.024168
srch_query_affinity_score,0.014776,0.028126,0.011806,-0.029269,0.034492,0.075046,0.021229,0.024168,1.000000

In [47]:
correlation_list = []

for i in corrMatrix.columns:
    for j in corrMatrix.index:
        if i != j and [j, i] not in [[x[0], x[1]] for x in correlation_list]:
            correlation_list.append([i, j, corrMatrix[i][j]]) 
correlation_list.sort(key=lambda x: abs(x[2]), reverse=True)
correlation_list

[['prop_starrating', 'prop_review_score', 0.39358092210426293],
 ['prop_location_score1', 'prop_location_score2', 0.3895818017005171],
 ['prop_starrating', 'prop_location_score1', 0.31901013492508373],
 ['prop_country_id', 'prop_brand_bool', 0.24956443723617222],
 ['prop_country_id', 'prop_starrating', -0.203205862197898],
 ['prop_brand_bool', 'prop_location_score1', -0.19755695509103913],
 ['prop_country_id', 'prop_location_score1', -0.18570445311755832],
 ['prop_location_score1', 'promotion_flag', 0.18542103038666877],
 ['prop_brand_bool', 'promotion_flag', -0.17833561101157733],
 ['prop_starrating', 'prop_log_historical_price', 0.17205445777496373],
 ['prop_starrating', 'promotion_flag', 0.1601983658928552],
 ['prop_review_score', 'prop_brand_bool', 0.13447404423747233],
 ['prop_location_score1', 'prop_log_historical_price', 0.13378749243912386],
 ['prop_review_score', 'prop_location_score1', 0.1207473606409443],
 ['prop_brand_bool', 'prop_location_score2', -0.10613995031173445],
 ['prop_review_score', 'prop_log_historical_price', 0.10542130898935748],
 ['prop_country_id', 'promotion_flag', -0.10047589487944188],
 ['prop_starrating', 'prop_location_score2', 0.09541056026887862],
 ['prop_location_score2', 'srch_query_affinity_score', 0.07504568871158258],
 ['prop_review_score', 'prop_location_score2', 0.05863833521329429],
 ['prop_location_score2', 'prop_log_historical_price', 0.054839824654592306],
 ['prop_location_score2', 'promotion_flag', 0.051506455383545806],
 ['prop_location_score1', 'srch_query_affinity_score', 0.03449170948488406],
 ['prop_log_historical_price', 'promotion_flag', 0.031190355346765796],
 ['prop_brand_bool', 'srch_query_affinity_score', -0.029269128216538383],
 ['prop_starrating', 'srch_query_affinity_score', 0.028126494141824807],
 ['prop_brand_bool', 'prop_log_historical_price', -0.02536283787186638],
 ['prop_country_id', 'prop_location_score2', -0.024933580114764917],
 ['promotion_flag', 'srch_query_affinity_score', 0.02416817808290468],
 ['prop_log_historical_price',
  'srch_query_affinity_score',
  0.02122934946925079],
 ['prop_country_id', 'prop_log_historical_price', -0.018883086153014414],
 ['prop_country_id', 'srch_query_affinity_score', 0.014775651335343578],
 ['prop_review_score', 'promotion_flag', 0.012446577384450761],
 ['prop_review_score', 'srch_query_affinity_score', 0.011805927589234367],
 ['prop_country_id', 'prop_review_score', -0.00822273411727357],
 ['prop_starrating', 'prop_brand_bool', -0.0027763397687602795]]

In [24]:
correlation_ranking_dataframe = pd.DataFrame(correlation_list, columns=['attribute_1', 'attribute_2', 'correlation'])

In [26]:
correlation_ranking_dataframe.to_csv('correlation.csv', sep=',')