In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

Read Data From CSV

In [10]:
df = pd.read_pickle('dummy_data.pkl')
print(df)

     srch_id            date_time  site_id  visitor_location_country_id  \
0          1  2013-04-04 08:32:15       12                          187
1          1  2013-04-04 08:32:15       12                          187
2          1  2013-04-04 08:32:15       12                          187
3          1  2013-04-04 08:32:15       12                          187
4          1  2013-04-04 08:32:15       12                          187
5          1  2013-04-04 08:32:15       12                          187
6          1  2013-04-04 08:32:15       12                          187
7          1  2013-04-04 08:32:15       12                          187
8          1  2013-04-04 08:32:15       12                          187
9          1  2013-04-04 08:32:15       12                          187
10         1  2013-04-04 08:32:15       12                          187
11         1  2013-04-04 08:32:15       12                          187
12         1  2013-04-04 08:32:15       12                          187
13         1  2013-04-04 08:32:15       12                          187
14         1  2013-04-04 08:32:15       12                          187
15         1  2013-04-04 08:32:15       12                          187
16         1  2013-04-04 08:32:15       12                          187
17         1  2013-04-04 08:32:15       12                          187
18         1  2013-04-04 08:32:15       12                          187
19         1  2013-04-04 08:32:15       12                          187
20         1  2013-04-04 08:32:15       12                          187
21         1  2013-04-04 08:32:15       12                          187
22         1  2013-04-04 08:32:15       12                          187
23         1  2013-04-04 08:32:15       12                          187
24         1  2013-04-04 08:32:15       12                          187
25         1  2013-04-04 08:32:15       12                          187
26         1  2013-04-04 08:32:15       12                          187
27         1  2013-04-04 08:32:15       12                          187
28         4  2012-12-31 08:59:22        5                          219
29         4  2012-12-31 08:59:22        5                          219
..       ...                  ...      ...                          ...
970       75  2013-05-04 19:20:52        5                          219
971       75  2013-05-04 19:20:52        5                          219
972       75  2013-05-04 19:20:52        5                          219
973       75  2013-05-04 19:20:52        5                          219
974       75  2013-05-04 19:20:52        5                          219
975       75  2013-05-04 19:20:52        5                          219
976       75  2013-05-04 19:20:52        5                          219
977       75  2013-05-04 19:20:52        5                          219
978       75  2013-05-04 19:20:52        5                          219
979       75  2013-05-04 19:20:52        5                          219
980       75  2013-05-04 19:20:52        5                          219
981       75  2013-05-04 19:20:52        5                          219
982       75  2013-05-04 19:20:52        5                          219
983       75  2013-05-04 19:20:52        5                          219
984       75  2013-05-04 19:20:52        5                          219
985       75  2013-05-04 19:20:52        5                          219
986       75  2013-05-04 19:20:52        5                          219
987       75  2013-05-04 19:20:52        5                          219
988       75  2013-05-04 19:20:52        5                          219
989       75  2013-05-04 19:20:52        5                          219
990       75  2013-05-04 19:20:52        5                          219
991       75  2013-05-04 19:20:52        5                          219
992       75  2013-05-04 19:20:52        5                          219
993       78  2012-12-21 05:30:35        5                          205
994       78  2012-12-21 05:30:35        5                          205
995       78  2012-12-21 05:30:35        5                          205
996       78  2012-12-21 05:30:35        5                          205
997       78  2012-12-21 05:30:35        5                          205
998       78  2012-12-21 05:30:35        5                          205
999       78  2012-12-21 05:30:35        5                          205

     visitor_hist_starrating  visitor_hist_adr_usd  prop_country_id  prop_id  \
0                        NaN                   NaN              219      893
1                        NaN                   NaN              219    10404
2                        NaN                   NaN              219    21315
3                        NaN                   NaN              219    27348
4                        NaN                   NaN              219    29604
5                        NaN                   NaN              219    30184
6                        NaN                   NaN              219    44147
7                        NaN                   NaN              219    50984
8                        NaN                   NaN              219    53341
9                        NaN                   NaN              219    56880
10                       NaN                   NaN              219    59267
11                       NaN                   NaN              219    59526
12                       NaN                   NaN              219    68914
13                       NaN                   NaN              219    74474
14                       NaN                   NaN              219    81437
15                       NaN                   NaN              219    85728
16                       NaN                   NaN              219    88096
17                       NaN                   NaN              219    88127
18                       NaN                   NaN              219    88218
19                       NaN                   NaN              219    89073
20                       NaN                   NaN              219    95166
21                       NaN                   NaN              219    95307
22                       NaN                   NaN              219    97247
23                       NaN                   NaN              219   107872
24                       NaN                   NaN              219   111000
25                       NaN                   NaN              219   111106
26                       NaN                   NaN              219   114766
27                       NaN                   NaN              219   122844
28                       NaN                   NaN              219     3625
29                       NaN                   NaN              219    11622
..                       ...                   ...              ...      ...
970                      NaN                   NaN              100    59204
971                      NaN                   NaN              100    63519
972                      NaN                   NaN              100    64017
973                      NaN                   NaN              100    69149
974                      NaN                   NaN              219    81352
975                      NaN                   NaN              100    85657
976                      NaN                   NaN              219    87171
977                      NaN                   NaN              100    94850
978                      NaN                   NaN              100    96517
979                      NaN                   NaN              100   100080
980                      NaN                   NaN              100   114067
981                      NaN                   NaN              100   114201
982                      NaN                   NaN              100   115994
983                      NaN                   NaN              219   116668
984                      NaN                   NaN              100   118722
985                      NaN                   NaN              100   119002
986                      NaN                   NaN              100   122468
987                      NaN                   NaN              219   126555
988                      NaN                   NaN              219   128481
989                      NaN                   NaN              100   132664
990                      NaN                   NaN              100   133846
991                      NaN                   NaN              219   138447
992                      NaN                   NaN              100   139596
993                      NaN                   NaN               15     9246
994                      NaN                   NaN               15    10223
995                      NaN                   NaN               15    16549
996                      NaN                   NaN               15    31638
997                      NaN                   NaN               15    35509
998                      NaN                   NaN               15    35871
999                      NaN                   NaN               15    41413

     prop_starrating  prop_review_score      ...       \
0                  3                3.5      ...
1                  4                4.0      ...
2                  3                4.5      ...
3                  2                4.0      ...
4                  4                3.5      ...
5                  4                4.5      ...
6                  3                3.5      ...
7                  2                0.0      ...
8                  4                4.0      ...
9                  4                4.0      ...
10                 3                0.0      ...
11                 3                3.5      ...
12                 2                3.0      ...
13                 3                4.5      ...
14                 3                4.0      ...
15                 2                3.0      ...
16                 4                4.0      ...
17                 3                3.0      ...
18                 4                3.5      ...
19                 4                4.0      ...
20                 3                4.0      ...
21                 4                3.5      ...
22                 2                3.5      ...
23                 2                3.5      ...
24                 3                4.5      ...
25                 3                2.5      ...
26                 2                3.5      ...
27                 3                4.5      ...
28                 4                4.0      ...
29                 4                4.0      ...
..               ...                ...      ...
970                2                3.5      ...
971                2                2.5      ...
972                4                4.0      ...
973                2                3.0      ...
974                2                3.0      ...
975                2                2.5      ...
976                3                3.5      ...
977                3                4.0      ...
978                3                4.0      ...
979                3                3.5      ...
980                3                4.0      ...
981                2                4.0      ...
982                2                3.5      ...
983                2                3.0      ...
984                3                4.5      ...
985                4                4.0      ...
986                2                4.0      ...
987                2                3.5      ...
988                4                4.5      ...
989                2                3.5      ...
990                3                4.0      ...
991                2                2.5      ...
992                3                2.5      ...
993                5                5.0      ...
994                4                4.5      ...
995                4                3.0      ...
996                5                4.5      ...
997                5                4.5      ...
998                5                4.5      ...
999                4                3.5      ...

     comp6_rate_percent_diff  comp7_rate  comp7_inv  comp7_rate_percent_diff  \
0                        NaN         NaN        NaN                      NaN
1                        NaN         NaN        NaN                      NaN
2                        NaN         NaN        NaN                      NaN
3                        NaN         NaN        NaN                      NaN
4                        NaN         NaN        NaN                      NaN
5                        NaN         NaN        NaN                      NaN
6                        NaN         NaN        NaN                      NaN
7                        NaN         NaN        NaN                      NaN
8                        NaN         NaN        NaN                      NaN
9                        NaN         NaN        NaN                      NaN
10                       NaN         NaN        NaN                      NaN
11                       NaN         NaN        NaN                      NaN
12                       NaN         NaN        NaN                      NaN
13                       NaN         NaN        NaN                      NaN
14                       NaN         NaN        NaN                      NaN
15                       NaN         NaN        NaN                      NaN
16                       NaN         NaN        NaN                      NaN
17                       NaN         NaN        NaN                      NaN
18                       NaN         NaN        NaN                      NaN
19                       NaN         NaN        NaN                      NaN
20                       NaN         NaN        NaN                      NaN
21                       NaN         NaN        NaN                      NaN
22                       NaN         NaN        NaN                      NaN
23                       NaN         NaN        NaN                      NaN
24                       NaN         NaN        NaN                      NaN
25                       NaN         NaN        NaN                      NaN
26                       NaN         NaN        NaN                      NaN
27                       NaN         NaN        NaN                      NaN
28                       NaN         NaN        NaN                      NaN
29                       NaN         NaN        NaN                      NaN
..                       ...         ...        ...                      ...
970                      NaN         NaN        NaN                      NaN
971                      NaN         NaN        NaN                      NaN
972                      NaN         NaN        NaN                      NaN
973                      NaN         NaN        NaN                      NaN
974                      NaN         NaN        NaN                      NaN
975                      NaN         NaN        NaN                      NaN
976                      NaN         NaN        NaN                      NaN
977                      NaN         NaN        NaN                      NaN
978                      NaN         NaN        NaN                      NaN
979                      NaN         NaN        NaN                      NaN
980                      NaN         NaN        NaN                      NaN
981                      NaN         NaN        NaN                      NaN
982                      NaN         NaN        NaN                      NaN
983                      NaN         NaN        NaN                      NaN
984                      NaN         NaN        NaN                      NaN
985                      NaN         NaN        NaN                      NaN
986                      NaN         NaN        NaN                      NaN
987                      NaN         NaN        NaN                      NaN
988                      NaN         NaN        NaN                      NaN
989                      NaN         NaN        NaN                      NaN
990                      NaN         NaN        NaN                      NaN
991                      NaN         NaN        NaN                      NaN
992                      NaN         NaN        NaN                      NaN
993                      NaN         NaN        NaN                      NaN
994                      NaN         NaN        NaN                      NaN
995                      NaN         NaN        NaN                      NaN
996                      NaN         0.0        0.0                      NaN
997                      NaN         NaN        NaN                      NaN
998                      NaN         NaN        NaN                      NaN
999                      NaN         1.0        0.0                     19.0

     comp8_rate  comp8_inv  comp8_rate_percent_diff  click_bool  \
0           0.0        0.0                      NaN           0
1           0.0        0.0                      NaN           0
2           0.0        0.0                      NaN           0
3          -1.0        0.0                      5.0           0
4           0.0        0.0                      NaN           0
5           0.0        0.0                      7.0           0
6           0.0        0.0                      NaN           0
7           NaN        NaN                      NaN           0
8           0.0        0.0                      6.0           0
9           0.0        0.0                      NaN           0
10          0.0        0.0                      NaN           0
11          1.0        0.0                     31.0           0
12          0.0        0.0                     11.0           1
13          0.0        0.0                      NaN           0
14          0.0        0.0                      NaN           0
15          0.0        0.0                      NaN           0
16          0.0        0.0                     15.0           0
17          0.0        0.0                      NaN           0
18          0.0        0.0                      NaN           0
19          0.0        0.0                      5.0           0
20          0.0        0.0                      NaN           0
21         -1.0        0.0                     27.0           0
22         -1.0        0.0                      5.0           0
23          0.0        0.0                     14.0           0
24          0.0        0.0                      NaN           0
25          0.0        0.0                      NaN           0
26          NaN        NaN                      NaN           0
27          0.0        0.0                      NaN           0
28          NaN        NaN                      NaN           0
29          NaN        NaN                      NaN           0
..          ...        ...                      ...         ...
970         NaN        NaN                      NaN           0
971         NaN        NaN                      NaN           0
972         NaN        NaN                      NaN           0
973         NaN        NaN                      NaN           0
974         NaN        NaN                      NaN           0
975         NaN        NaN                      NaN           0
976         NaN        NaN                      NaN           0
977         NaN        NaN                      NaN           0
978         NaN        NaN                      NaN           0
979         NaN        NaN                      NaN           0
980         NaN        NaN                      NaN           0
981         NaN        NaN                      NaN           0
982         NaN        NaN                      NaN           0

Correlation Matrix of Raw Data:

In [12]:
df.dropna(inplace=True,axis='columns')



corrMatrix = df.corr()
sns.heatmap(corrMatrix, annot=True)
fig = plt.gcf()
fig.set_size_inches(60, 60)
plt.show()

ValueError: zero-size array to reduction operation minimum which has no identity